### ISSUE TITLE
native example has no attribute IS31FL3741_FrameBuffer'

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_IS31FL3741#23]
```py
Adafruit CircuitPython 8.0.5 on 2023-03-31; Adafruit Feather ESP32S2 with ESP32S2
Board ID:adafruit_feather_esp32s2
```

https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3741/blob/5ac6531e26ecc462da9a21c5dca2d16be038c85d/examples/is31fl3741_native.py#L29

Was this supposed to be changed to pixelbuf?  I see no mention in the library or examples of a reference to IS31FL3741_FrameBuffer.
```py
is31_fb = adafruit_is31fl3741.IS31FL3741_FrameBuffer(
    width=54,
    height=15,
    is31=is31,
    scale=True,
    gamma=True,
    mapping=glassesmatrix_ledmap_no_ring,
)
```
`AttributeError: 'module' object has no attribute 'IS31FL3741_FrameBuffer'`

**Comment by tekktrik** [comment]
I believe `IS31FL3741_FrameBuffer` is only available natively from applicable CircuitPython firmware:  https://docs.circuitpython.org/en/latest/shared-bindings/is31fl3741/index.html#is31fl3741.IS31FL3741_FrameBuffer

Not exactly sure how it relates to the `PixelBuffer`, but based on how different the arguments, I think they're meant to be distinctly different.

**Comment by tekktrik** [comment]
I think additional information about compatibility is good, is that something you're interesting in helping out with?

**Comment by DJDevon3** [comment]
@tekktrik It only needs a comment in the header.  I can do that sure.
